### ISSUE TITLE
17 bytes read on a total of undefined expected bytes

### ISSUE THREAD

**Issue by kihotx** [mackojar/satel_ethm#3]
Dear 

i'm stucked with:

`
Unexpected error fetching Satel data: 17 bytes read on a total of undefined expected bytes
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/satel_ethm/coordinator.py", line 100, in _async_update_data
    newData = await self._satel.executeCommand(commands.listDataAvailable())
  File "/config/custom_components/satel_ethm/satel/satel.py", line 58, in executeCommand
    raise e
  File "/config/custom_components/satel_ethm/satel/satel.py", line 54, in executeCommand
    return await self._receive_response()
  File "/config/custom_components/satel_ethm/satel/satel.py", line 67, in _receive_response
    resp = await self._read_data()
  File "/config/custom_components/satel_ethm/satel/satel.py", line 75, in _read_data
    data = await self._reader.readuntil(b"\xFE\x0D")
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 613, in readuntil
    raise exceptions.IncompleteReadError(chunk, None)
asyncio.exceptions.IncompleteReadError: 17 bytes read on a total of undefined expected bytes
`

and integration fails to run. Can you support please?

**Comment by maciejjarkowski-a4bee** [comment]
Looks strange. Actually currently the type of Satel module is hardcoded. And it might cause some problems, but anyway, depending on the module version there is always no more then 14 bytes in the response (if I count correctly).
In your case it is 17 and there is still no end sequence (FE, 0D). Looks strange.
Can you debug/dig into satel.py:_read_data() to see what exactly was read from Satel?

**Comment by kihotx** [comment]
Hi Maciej, 

configuration runs smoothly, but realod of integration causes described issue. 

`
2023-08-08 21:40:02.358 WARNING (MainThread) [homeassistant.config_entries] Config entry 'INTEGRA_64' for satel_ethm integration not ready yet: 17 bytes read on a total of undefined expected bytes; Retrying in background
2023-08-08 21:40:07.612 ERROR (MainThread) [custom_components.satel_ethm.satel.satel] Error executing command: 17 bytes read on a total of undefined expected bytes
2023-08-08 21:40:07.614 ERROR (MainThread) [custom_components.satel_ethm.coordinator] Unexpected error fetching Satel data: 17 bytes read on a total of undefined expected bytes
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/satel_ethm/coordinator.py", line 100, in _async_update_data
newData = await self._satel.executeCommand(commands.listDataAvailable())
File "/config/custom_components/satel_ethm/satel/satel.py", line 58, in executeCommand
raise e
File "/config/custom_components/satel_ethm/satel/satel.py", line 54, in executeCommand
return await self._receive_response()
File "/config/custom_components/satel_ethm/satel/satel.py", line 67, in _receive_response
resp = await self._read_data()
File "/config/custom_components/satel_ethm/satel/satel.py", line 75, in _read_data
data = await self._reader.readuntil(b"\xFE\x0D")
File "/usr/local/lib/python3.10/asyncio/streams.py", line 613, in readuntil
raise exceptions.IncompleteReadError(chunk, None)
asyncio.exceptions.IncompleteReadError: 17 bytes read on a total of undefined expected bytes
`
 
for example for 'arming' log looks like follow:

`
2023-08-08 21:51:07.312 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] SatelCoordinator _async_update_data
2023-08-08 21:51:07.313 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Already connected to Satel
2023-08-08 21:51:07.313 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x7f\x00\x4f\x8b\xfe\x0d (len: 8)
2023-08-08 21:51:07.314 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-08 21:51:07.334 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x7f\x80\x23\x00\xff\x5f\xf3\x09\x07\xfe\x0d
2023-08-08 21:51:07.335 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Finished fetching Satel data in 0.022 seconds (success: True)
2023-08-08 21:51:15.474 INFO (MainThread) [custom_components.satel_ethm.alarm_control_panel] Send arm home command. Code: 15959
2023-08-08 21:51:17.312 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] SatelCoordinator _async_update_data
2023-08-08 21:51:17.312 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Already connected to Satel
2023-08-08 21:51:17.312 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x7f\x00\x4f\x8b\xfe\x0d (len: 8)
2023-08-08 21:51:17.313 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-08 21:51:17.330 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x7f\x80\x23\x00\xff\x5f\xf3\x09\x07\xfe\x0d
2023-08-08 21:51:17.330 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Finished fetching Satel data in 0.018 seconds (success: True)
`

it seems like data received from satel was correct:

`
2023-08-08 21:51:17.330 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x7f\x80\x23\x00\xff\x5f\xf3\x09\x07\xfe\x0d
`

but unfortunately no action on satel.

Sensors seems to work, and shows 'violated', after first configuration of integration. 

`
2023-08-08 22:11:27.348 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Finished fetching Satel data in 0.037 seconds (success: True)
2023-08-08 22:11:37.312 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] SatelCoordinator _async_update_data
2023-08-08 22:11:37.312 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Already connected to Satel
2023-08-08 22:11:37.312 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x7f\x00\x4f\x8b\xfe\x0d (len: 8)
2023-08-08 22:11:37.313 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-08 22:11:37.343 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x7f\x81\x23\x00\xff\x7f\xf3\x08\xa6\xfe\x0d
2023-08-08 22:11:37.343 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x00\xd7\xe2\xfe\x0d (len: 7)
2023-08-08 22:11:37.346 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-08 22:11:37.385 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x2c\x67\xfe\x0d
2023-08-08 22:11:37.386 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Zones violated: [2]
2023-08-08 22:11:37.386 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x25\xd8\x07\xfe\x0d (len: 7)
2023-08-08 22:11:37.388 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-08 22:11:37.407 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x25\x00\x00\x00\x00\x7f\x80\xfe\x0d
2023-08-08 22:11:37.407 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Partitions violated zones: []
2023-08-08 22:11:37.408 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Finished fetching Satel data in 0.096 seconds (success: True)
2023-08-08 22:11:47.312 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] SatelCoordinator _async_update_data
2023-08-08 22:11:47.313 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Already connected to Satel
2023-08-08 22:11:47.313 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x7f\x00\x4f\x8b\xfe\x0d (len: 8)
2023-08-08 22:11:47.314 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-08 22:11:47.340 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x7f\x81\x23\x00\xff\x5f\xf3\x08\xe6\xfe\x0d
2023-08-08 22:11:47.341 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x00\xd7\xe2\xfe\x0d (len: 7)
2023-08-08 22:11:47.342 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-08 22:11:47.383 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x32\x86\xfe\x0d
2023-08-08 22:11:47.383 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Zones violated: []
2023-08-08 22:11:47.384 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Finished fetching Satel data in 0.072 seconds (success: True)
2023-08-08 22:11:57.312 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] SatelCoordinator _async_update_data
2023-08-08 22:11:57.312 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Already connected to Satel
2023-08-08 22:11:57.313 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x7f\x00\x4f\x8b\xfe\x0d (len: 8)
2023-08-08 22:11:57.316 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-08 22:11:57.337 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x7f\x80\x23\x00\xff\x5f\xf3\x09\x07\xfe\x0d
2023-08-08 22:11:57.337 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Finished fetching Satel data in 0.025 seconds (success: True)
`

form Arm command:

`
2023-08-09 10:57:46.267 INFO (MainThread) [custom_components.satel_ethm.alarm_control_panel] Send arm away command. Code: 15959
2023-08-09 10:57:54.489 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] SatelCoordinator _async_update_data
2023-08-09 10:57:54.489 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Already connected to Satel
2023-08-09 10:57:54.489 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x7f\x00\x4f\x8b\xfe\x0d (len: 8)
2023-08-09 10:57:54.491 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-09 10:57:54.522 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x7f\x80\x23\x00\xff\x5f\xf3\x09\x07\xfe\x0d
2023-08-09 10:57:54.522 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Finished fetching Satel data in 0.033 seconds (success: True)
2023-08-09 10:58:04.490 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] SatelCoordinator _async_update_data

-- DIFFERENT CODE

2023-08-09 11:34:30.011 INFO (MainThread) [custom_components.satel_ethm.alarm_control_panel] Send arm home command. Code: 0000
2023-08-09 11:34:34.490 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] SatelCoordinator _async_update_data
2023-08-09 11:34:34.490 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Already connected to Satel
2023-08-09 11:34:34.490 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x7f\x00\x4f\x8b\xfe\x0d (len: 8)
2023-08-09 11:34:34.491 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-09 11:34:34.511 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x7f\x80\x23\x00\xff\x5f\xf3\x09\x07\xfe\x0d
2023-08-09 11:34:34.512 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Finished fetching Satel data in 0.022 seconds (success: True)
2023-08-09 11:34:34.936 INFO (MainThread) [custom_components.satel_ethm.alarm_control_panel] Send arm home command. Code: 2709
`

for Disarm command: 

`
2023-08-09 11:14:11.921 INFO (MainThread) [custom_components.satel_ethm.alarm_control_panel] Send disarm command. Code: 15959
2023-08-09 11:14:14.489 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] SatelCoordinator _async_update_data
2023-08-09 11:14:14.490 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Already connected to Satel
2023-08-09 11:14:14.490 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x7f\x00\x4f\x8b\xfe\x0d (len: 8)
2023-08-09 11:14:14.491 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-09 11:14:14.526 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x7f\x81\x23\x00\xff\x7f\xf3\x08\xa6\xfe\x0d
2023-08-09 11:14:14.527 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x00\xd7\xe2\xfe\x0d (len: 7)
2023-08-09 11:14:14.531 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-09 11:14:14.568 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x32\x86\xfe\x0d
`

Thanks,

Maciej

**Comment by mackojar** [comment]
What's important for me is: "Sensors seems to work, and shows 'violated', after first configuration of integration. After HA reboot - stops.". So that's means that there is some problem when HA is disconnecting from Satel.

Can you verify if you really are disconnected from Satel? 
As far as I remember Satel do not allow more then one connection at the same time.
Maybe you have to wait for a few seconds before starting HA again?

Is your ETHM-1 or INTEGRA firmware up to date?

**Comment by kihotx** [comment]
Yes it seems to work after some time. 

Can you also support with arming/disarming as it seems not to work ?

**Comment by mackojar** [comment]
I did not play with arming and disarming. I do not have any experience about that.
What do you mean by "not working"?

**Comment by kihotx** [comment]
it does not arm / disarm alarm, when sending the command. Can you support with debug:

`2023-08-09 10:57:46.267 INFO (MainThread) [custom_components.satel_ethm.alarm_control_panel] Send arm away command. Code: 15959
2023-08-09 10:57:54.489 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] SatelCoordinator _async_update_data
2023-08-09 10:57:54.489 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Already connected to Satel
2023-08-09 10:57:54.489 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Sending data: \xfe\xfe\x7f\x00\x4f\x8b\xfe\x0d (len: 8)
2023-08-09 10:57:54.491 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Waiting for response...
2023-08-09 10:57:54.522 DEBUG (MainThread) [custom_components.satel_ethm.satel.satel] Received data: \xfe\xfe\x7f\x80\x23\x00\xff\x5f\xf3\x09\x07\xfe\x0d
2023-08-09 10:57:54.522 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] Finished fetching Satel data in 0.033 seconds (success: True)
2023-08-09 10:58:04.490 DEBUG (MainThread) [custom_components.satel_ethm.coordinator] SatelCoordinator _async_update_data
`

it seems like every time command is sent:

`\xfe\xfe\x7f\x00\x4f\x8b\xfe\x0d`

even for different codes. Ex. code '19595' and '0000' send the same payload.

**Comment by mackojar** [comment]
Well, as described in the Readme.md: arm/disarm commands are not implemented. There are only placeholders - they just log the code you've entered. The command you can (x7F) see is periodically sent to get the info about any new data available.
